package cmd

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

const defaultConfigPath = "~/.srekit.yaml"

func newConfigCmd() *cobra.Command {
	c := &cobra.Command{
		Use:   "config",
		Short: "Manage the srekit user configuration file",
		Long:  "Scaffold or inspect ~/.srekit.yaml — author, email, and an optional default templates_dir.",
	}
	c.AddCommand(newConfigInitCmd())
	return c
}

func newConfigInitCmd() *cobra.Command {
	var (
		author       string
		email        string
		templatesDir string
		force        bool
		yes          bool
	)
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create ~/.srekit.yaml interactively",
		Long: `Walk the user through filling in ~/.srekit.yaml — author, email,
and an optional default templates_dir. Defaults are pulled from
'git config user.name' / 'user.email'. Pass --yes (or run with a
non-TTY stdin) to skip the prompts and write straight from the
flag/git-config values.

The target path follows --config: if --config FILE is set on the
root command, init writes there; otherwise it writes ~/.srekit.yaml.`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runConfigInit(cmd, configInitOpts{
				author:       author,
				email:        email,
				templatesDir: templatesDir,
				force:        force,
				yes:          yes,
			})
		},
	}
	cmd.Flags().StringVar(&author, "author", "", "author name (default: git config user.name)")
	cmd.Flags().StringVar(&email, "email", "", "author email (default: git config user.email)")
	cmd.Flags().StringVar(&templatesDir, "templates-dir", "", "default templates directory (optional)")
	cmd.Flags().BoolVar(&force, "force", false, "overwrite an existing config file")
	cmd.Flags().BoolVarP(&yes, "yes", "y", false, "non-interactive: accept defaults without prompting")
	return cmd
}

type configInitOpts struct {
	author       string
	email        string
	templatesDir string
	force        bool
	yes          bool
}

func runConfigInit(cmd *cobra.Command, opts configInitOpts) error {
	target, err := configTargetPath(cmd)
	if err != nil {
		return err
	}
	if _, err := os.Stat(target); err == nil && !opts.force {
		return fmt.Errorf("%s already exists; pass --force to overwrite", target)
	} else if err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}

	ctx := cmd.Context()
	author := firstNonEmpty(opts.author, gitConfigValue(ctx, "user.name"))
	email := firstNonEmpty(opts.email, gitConfigValue(ctx, "user.email"))
	templatesDir := opts.templatesDir

	interactive := !opts.yes && stdinIsTerminal(cmd.InOrStdin())
	if interactive {
		r := bufio.NewReader(cmd.InOrStdin())
		out := cmd.OutOrStdout()
		if author, err = promptLine(r, out, "Author name", author); err != nil {
			return err
		}
		if email, err = promptLine(r, out, "Email", email); err != nil {
			return err
		}
		if templatesDir, err = promptLine(r, out,
			"Templates dir (leave empty to use embedded templates only)",
			templatesDir); err != nil {
			return err
		}
	}

	if author == "" {
		return errors.New("author is required (pass --author or set git config user.name)")
	}
	if email == "" {
		return errors.New("email is required (pass --email or set git config user.email)")
	}

	body := renderConfigYAML(author, email, templatesDir)
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return fmt.Errorf("create parent dir: %w", err)
	}
	if err := os.WriteFile(target, []byte(body), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", target, err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "Wrote %s\n", target)
	return nil
}

func configTargetPath(cmd *cobra.Command) (string, error) {
	if f := cmd.Root().PersistentFlags().Lookup("config"); f != nil {
		if v := f.Value.String(); v != "" {
			return expandHome(v)
		}
	}
	return expandHome(defaultConfigPath)
}

func promptLine(r *bufio.Reader, out io.Writer, label, def string) (string, error) {
	if def != "" {
		fmt.Fprintf(out, "%s [%s]: ", label, def)
	} else {
		fmt.Fprintf(out, "%s: ", label)
	}
	line, err := r.ReadString('\n')
	if err != nil && !errors.Is(err, io.EOF) {
		return "", err
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return def, nil
	}
	return line, nil
}

func stdinIsTerminal(in io.Reader) bool {
	f, ok := in.(*os.File)
	if !ok {
		return false
	}
	fi, err := f.Stat()
	if err != nil {
		return false
	}
	return fi.Mode()&os.ModeCharDevice != 0
}

func renderConfigYAML(author, email, templatesDir string) string {
	var b strings.Builder
	b.WriteString("# srekit user config — generated by `srekit config init` (safe to edit by hand)\n")
	fmt.Fprintf(&b, "author: %s\n", yamlString(author))
	fmt.Fprintf(&b, "email: %s\n", yamlString(email))
	if templatesDir != "" {
		fmt.Fprintf(&b, "templates_dir: %s\n", yamlString(templatesDir))
	} else {
		b.WriteString("# templates_dir: ~/.srekit/templates  # optional; uncomment to override embedded templates\n")
	}
	return b.String()
}

// yamlString quotes a value when it contains characters that would otherwise
// need YAML escaping. For typical names and paths the bare form is fine.
func yamlString(s string) string {
	if s == "" || strings.ContainsAny(s, ":#\"'\n\t") || strings.HasPrefix(s, " ") || strings.HasSuffix(s, " ") {
		return fmt.Sprintf("%q", s)
	}
	return s
}

func firstNonEmpty(xs ...string) string {
	for _, x := range xs {
		if s := strings.TrimSpace(x); s != "" {
			return s
		}
	}
	return ""
}

// gitConfigValue returns the value of a git config key, or "" if git is
// unavailable / the key is unset. Standalone to keep this command resilient
// when meta.gitRunner is stubbed out by an unrelated test.
func gitConfigValue(ctx context.Context, key string) string {
	out, err := exec.CommandContext(ctx, "git", "config", "--get", key).Output()
	if err != nil {
		return ""
	}
	return strings.TrimSpace(string(out))
}
